# Task - 3 Logistic Regression using Built-in function

In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer

In [ ]:
cancer_df = load_breast_cancer(as_frame=True)
df = cancer_df.frame

In [ ]:
df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,1

In [ ]:
df.shape

(569, 31)

In [ ]:
X = df.iloc[:,:-1]
y = df["target"]

In [ ]:
from sklearn.preprocessing import StandardScaler

le = StandardScaler()
X = le.fit_transform(X)

In [ ]:
X

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]], shape=(569, 30))

In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42,stratify=y)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train,y_train)

pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,r2_score
print("Accuracy:")
print(accuracy_score(y_test, pred))
print("\n")
print("Confusion Matrix:")
print(confusion_matrix(y_test, pred))
print("\n")
print("Classification Report:")
print(classification_report(y_test, pred))

Accuracy:
0.9824561403508771


Confusion Matrix:
[[41  1]
 [ 1 71]]


Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98        42
           1       0.99      0.99      0.99        72

    accuracy                           0.98       114
   macro avg       0.98      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

params = {
    'C': [0.01, 0.1, 1, 10, 100],
    'solver': ['liblinear', 'lbfgs']
}

grid = GridSearchCV(
    LogisticRegression(max_iter=1000),
    params,
    cv=5,
    scoring='accuracy'
)

grid.fit(X_train, y_train)

print("Best parameters:", grid.best_params_)
print("Best CV score:", grid.best_score_)

Best parameters: {'C': 0.1, 'solver': 'lbfgs'}
Best CV score: 0.9802197802197803

-

# Lab Task 1: Perceptron for Binary Classification Without Using Built-in Libraries

In [ ]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

In [ ]:
iris = load_iris(as_frame = True)
df_iris = iris.frame
df_iris

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [ ]:
df_iris[df_iris["target"] == 2]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
100,6.3,3.3,6.0,2.5,2
101,5.8,2.7,5.1,1.9,2
102,7.1,3.0,5.9,2.1,2
103,6.3,2.9,5.6,1.8,2
104,6.5,3.0,5.8,2.2,2
105,7.6,3.0,6.6,2.1,2
106,4.9,2.5,4.5,1.7,2
107,7.3,2.9,6.3,1.8,2
108,6.7,2.5,5.8,1.8,2
109,7.2,3.6,6.1,2.5,2
110,6.5,3.2,5.1,2.0,2
111,6.4,2.7,5.3,1.9,2
112,6.8,3.0,5.5,2.1,2
113,5.7,2.5,5.0,2.0,2
114,5.8,2.8,5.1,2.4,2
115,6.4,3.2,5.3,2.3,2
116,6.5,3.0,5.5,1.8,2
117,7.7,3.8,6.7,2.2,2
118,7.7,2.6,6.9,2.3,2
119,6.0,2.2,5.0,1.5,2
120,6.9,3.2,5.7,2.3,2
121,5.6,2.8,4.9,2.0,2
122,7.7,2.8,6.7,2.0,2
123,6.3,2.7,4.9,1.8,2
124,6.7,3.3,5.7,2.1,2
125,7.2,3.2,6.0,1.8,2
126,6.2,2.8,4.8,1.8,2
127,6.1,3.0,4.9,1.8,2
128,6.4,2.8,5.6,2.1,2
129,7.2,3.0,5.8,1.6,2
130,7.4,2.8,6.1,1.9,2
131,7.9,3.8,6.4,2.0,2
132,6.4,2.8,5.6,2.2,2
133,6.3,2.8,5.1,1.5,2
134,6.1,2.6,5.6,1.4,2
135,7.7,3.0,6.1,2.3,2
136,6.3,3.4,5.6,2.4,2
137,6.4,3.1,5.5,1.8,2
138,6.0,3.0,4.8,1.8,2
139,6.9,3.1,5.4,2.1,2
140,6.7,3.1,5.6,2.4,2
141,6.9,3.1,5.1,2.3,2
142,5.8,2.7,5.1,1.9,2
143,6.8,3.2,5.9,2.3,2
144,6.7,3.3,5.7,2.5,2
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [ ]:
df_iris = df_iris[df_iris["target"]!=2]
df_iris

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
95,5.7,3.0,4.2,1.2,1
96,5.7,2.9,4.2,1.3,1
97,6.2,2.9,4.3,1.3,1
98,5.1,2.5,3.0,1.1,1
99,5.7,2.8,4.1,1.3,1

In [9]:
X = df_iris.drop("target",axis=1)
y = df_iris["target"]

In [10]:
X

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
..                ...               ...                ...               ...
95                5.7               3.0                4.2               1.2
96                5.7               2.9                4.2               1.3
97                6.2               2.9                4.3               1.3
98                5.1               2.5                3.0               1.1
99                5.7               2.8                4.1               1.3

[100 rows x 4 columns]

In [11]:
y

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: target, Length: 100, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42,stratify=y)

In [48]:
learning_rate = 0.1
epochs = 10

In [49]:
w = np.zeros(X_train.shape[1])
b = 0

In [50]:
def step_function(x):
  if x >= 0:
    return 1
  else:
    return 0

In [51]:
def predict(x):
  z = np.dot(x,w) + b
  return step_function(z)

In [59]:
for epoch in range(epochs):

    for x, target in zip(X_train.values, y_train.values):

        # Weighted sum
        z = np.dot(x, w) + b

        # Prediction
        prediction = step_function(z)

        # Error
        error = target - prediction

        # Perceptron weight update rule
        w = w + learning_rate * error * x

        # Bias update
        b = b + learning_rate * error
    print(w,b)

    print(f"Epoch {epoch+1}/{epochs} -> Error: {error}")

[-0.14 -0.69  0.97  0.42] -0.1
Epoch 1/10 -> Error: 0
[-0.14 -0.69  0.97  0.42] -0.1
Epoch 2/10 -> Error: 0
[-0.14 -0.69  0.97  0.42] -0.1
Epoch 3/10 -> Error: 0
[-0.14 -0.69  0.97  0.42] -0.1
Epoch 4/10 -> Error: 0
[-0.14 -0.69  0.97  0.42] -0.1
Epoch 5/10 -> Error: 0
[-0.14 -0.69  0.97  0.42] -0.1
Epoch 6/10 -> Error: 0
[-0.14 -0.69  0.97  0.42] -0.1
Epoch 7/10 -> Error: 0
[-0.14 -0.69  0.97  0.42] -0.1
Epoch 8/10 -> Error: 0
[-0.14 -0.69  0.97  0.42] -0.1
Epoch 9/10 -> Error: 0
[-0.14 -0.69  0.97  0.42] -0.1
Epoch 10/10 -> Error: 0

In [53]:
y_pred = []

for x in X_test.values:
  o = predict(x)
  y_pred.append(o)

y_pred = np.array(y_pred)

In [54]:
p = {
    "Actual" : y_test,
    "Predicted" : y_pred
}
p = pd.DataFrame(p)

In [55]:
p

    Actual  Predicted
57       1          1
77       1          1
63       1          1
51       1          1
7        0          0
14       0          0
20       0          0
75       1          1
18       0          0
22       0          0
42       0          0
58       1          1
49       0          0
38       0          0
10       0          0
93       1          1
69       1          1
28       0          0
56       1          1
84       1          1

In [56]:
accuracy = np.mean(y_pred == y_test)*100
print("Accuracy:", accuracy)

Accuracy: 100.0

Analyze the effect of different learning rates and numbers of epochs.

In [63]:
learning_rates = [0.001, 0.01, 0.1, 1.0]
epochs_list = [5, 10, 20, 50]

for lr in learning_rates:

    for ep in epochs_list:

        weights = np.zeros(X_train.shape[1])
        bias = 0

        for epoch in range(ep):

            for x, target in zip(X_train.values, y_train.values):

                z = np.dot(x, weights) + bias
                prediction = step_function(z)

                error = target - prediction

                weights = weights + lr * error * x
                bias = bias + lr * error

        # Testing
        predictions = []

        for x in X_test.values:
            z = np.dot(x, weights) + bias
            predictions.append(step_function(z))

        predictions = np.array(predictions)

        accuracy = np.mean(predictions == y_test) * 100

        print(
            "Learning Rate:", lr,
            "Epochs:", ep,
            "Accuracy:", accuracy, "%"
        )

Learning Rate: 0.001 Epochs: 5 Accuracy: 100.0 %
Learning Rate: 0.001 Epochs: 10 Accuracy: 100.0 %
Learning Rate: 0.001 Epochs: 20 Accuracy: 100.0 %
Learning Rate: 0.001 Epochs: 50 Accuracy: 100.0 %
Learning Rate: 0.01 Epochs: 5 Accuracy: 100.0 %
Learning Rate: 0.01 Epochs: 10 Accuracy: 100.0 %
Learning Rate: 0.01 Epochs: 20 Accuracy: 100.0 %
Learning Rate: 0.01 Epochs: 50 Accuracy: 100.0 %
Learning Rate: 0.1 Epochs: 5 Accuracy: 100.0 %
Learning Rate: 0.1 Epochs: 10 Accuracy: 100.0 %
Learning Rate: 0.1 Epochs: 20 Accuracy: 100.0 %
Learning Rate: 0.1 Epochs: 50 Accuracy: 100.0 %
Learning Rate: 1.0 Epochs: 5 Accuracy: 100.0 %
Learning Rate: 1.0 Epochs: 10 Accuracy: 100.0 %
Learning Rate: 1.0 Epochs: 20 Accuracy: 100.0 %
Learning Rate: 1.0 Epochs: 50 Accuracy: 100.0 %

----------------------------------------------------

# Lab Task 2: Perceptron for Binary Classification Using a Built-in Library

In [3]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [4]:
iris = load_iris(as_frame = True)
df_i = iris.frame
df_i

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [5]:
df_i = df_i[df_i["target"]!=2]
df_i

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
95,5.7,3.0,4.2,1.2,1
96,5.7,2.9,4.2,1.3,1
97,6.2,2.9,4.3,1.3,1
98,5.1,2.5,3.0,1.1,1
99,5.7,2.8,4.1,1.3,1

In [6]:
X = df_i.drop("target",axis = 1)
y = df_i["target"]

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42,stratify=y)

In [13]:
from sklearn.linear_model import Perceptron
model = Perceptron(
    eta0=0.01,
    max_iter=20,
    random_state=42
)

# eta0=0.01 → learning rate = 0.01
# max_iter=20 → maximum 20 epochs
# random_state=42 → reproducible results

In [14]:
model.fit(X_train, y_train)

Perceptron(eta0=0.01, max_iter=20, random_state=42)

In [15]:
y_pred = model.predict(X_test)

In [23]:
p = {
    "Actual" : y_test,
    "Predicted" : y_pred
}
p = pd.DataFrame(p)
p

    Actual  Predicted
57       1          1
77       1          1
63       1          1
51       1          1
7        0          0
14       0          0
20       0          0
75       1          1
18       0          0
22       0          0
42       0          0
58       1          1
49       0          0
38       0          0
10       0          0
93       1          1
69       1          1
28       0          0
56       1          1
84       1          1

In [21]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0

In [25]:
print("Weights:")
print(model.coef_)

print("\nBias:")
print(model.intercept_)

Weights:
[[-0.021 -0.076  0.102  0.049]]

Bias:
[-0.01]

-

# Lab Task 4: Logistic Regression from Scratch

In [27]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [28]:
ir = load_iris(as_frame = True)
df = ir.frame
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [29]:
df = df[df["target"]!=2]
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
95,5.7,3.0,4.2,1.2,1
96,5.7,2.9,4.2,1.3,1
97,6.2,2.9,4.3,1.3,1
98,5.1,2.5,3.0,1.1,1
99,5.7,2.8,4.1,1.3,1

In [30]:
X = df.drop("target",axis = 1)
y = df["target"]

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42,stratify=y)

In [33]:
weights = np.zeros(X.shape[1])
bias = 0

In [34]:
learning_rate = 0.1
iterations = 1000

In [35]:
def sigmoid(z):
  return 1 / (1 + np.exp(-z))

In [36]:
n = len(y_train)

In [37]:
for i in range(iterations):
  z = np.dot(X_train.values,weights) + bias

  predictions = sigmoid(z)

  error = predictions - y_train

  # Gradient of weights
  dw = (1 / n) * np.dot(X_train.T, error)

  # Gradient of bias
  db = (1 / n) * np.sum(error)

  # Update weights and bias
  weights = weights - learning_rate * dw
  bias = bias - learning_rate * db

In [38]:
z_test = np.dot(X_test, weights) + bias

y_probability_test = sigmoid(z_test)

# Convert probabilities to class labels
y_pred = (y_probability_test >= 0.5).astype(int)

In [39]:
p = {
    "Actual" : y_test,
    "Predicted" : y_pred
}
p = pd.DataFrame(p)
p

    Actual  Predicted
57       1          1
77       1          1
63       1          1
51       1          1
7        0          0
14       0          0
20       0          0
75       1          1
18       0          0
22       0          0
42       0          0
58       1          1
49       0          0
38       0          0
10       0          0
93       1          1
69       1          1
28       0          0
56       1          1
84       1          1

In [43]:
accuracy = np.mean(y_pred == y_test) * 100

print("\nFrom Scratch Accuracy:", accuracy, "%")

From Scratch Accuracy: 100.0 %

Compare the results with a built-in Logistic Regression model

In [42]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

model = LogisticRegression()

model.fit(X_train, y_train)

y_pred_library = model.predict(X_test)

library_accuracy = accuracy_score(y_test, y_pred_library) * 100

print("Built-in Accuracy:", library_accuracy, "%")

Built-in Accuracy: 100.0 %